/*
 * ============================================================================
 * Program Name:   EECS 348 Assignment 3 - CEO Email Priority Queue
 *
 * Description:    C++ object-oriented program that prioritizes emails for a
 *                 busy company CEO. Emails are stored in a MaxHeap that is
 *                 built from scratch on top of a list (std::vector) and used
 *                 as a priority queue. Priority is decided first by sender
 *                 category (Boss > Subordinate > Peer > ImportantPerson >
 *                 OtherPerson) and then by date, so the newest email from a
 *                 category is read first.
 *
 * Inputs:         A test file of commands (EMAIL, NEXT, READ, COUNT). The
 *                 file name is passed as the first command-line argument; if
 *                 it is missing, the user is prompted to type it.
 *
 * Output:         Terminal output for the NEXT and COUNT commands (and an
 *                 error message if the file cannot be opened).
 *
 * Collaborators:  None
 *
 * Other Sources:  Code generated by Claude (Anthropic GenAI), accessed through
 *                 the Claude desktop app, from the Assignment 3 prompt.
 *
 * Author:         Erick Marte
 * Creation Date:  10-01-2026
 * Revision Date:  10-01-2026
 * Revisions:      Initial version generated by Claude.
 *
 * Build:          g++ -std=c++11 -Wall -o assignment3 claude_email_priority.cpp
 * Run:            ./assignment3 test.txt
 * ============================================================================
 */

#include <iostream>   // std::cout, std::cin, std::cerr for terminal I/O
#include <fstream>    // std::ifstream for reading the test file
#include <sstream>    // std::istringstream for parsing the date string
#include <string>     // std::string for text fields
#include <vector>     // std::vector is the list that backs the MaxHeap
#include <cstddef>    // std::size_t for heap indexes
#include <cctype>     // std::isspace for trimming whitespace
#include <utility>    // std::swap for exchanging heap elements

/* ----------------------------------------------------------------------------
 * Email class (source: Claude)
 * Stores one email and knows how to compare its priority with another email
 * and how to display itself in the required NEXT format.
 * ------------------------------------------------------------------------- */
class Email {
public:
    // Default constructor so Email can be stored in a std::vector
    Email() : rank_(0), dateKey_(0), sequence_(0) {}

    // Build an email from its three text fields plus its arrival order
    Email(const std::string& sender, const std::string& subject,
          const std::string& date, long sequence)
        : sender_(sender),                 // save sender category text
          subject_(subject),               // save subject line text
          date_(date),                     // save date text exactly as given
          rank_(categoryRank(sender)),     // convert category to a numeric rank
          dateKey_(dateToKey(date)),       // convert MM-DD-YYYY to YYYYMMDD
          sequence_(sequence) {}           // save arrival order for tie-breaks

    // operator< means "this email has LOWER priority than other"
    // The MaxHeap uses it to keep the highest-priority email at the root
    bool operator<(const Email& other) const {
        if (rank_ != other.rank_)              // different sender categories?
            return rank_ < other.rank_;        // lower rank = lower priority
        if (dateKey_ != other.dateKey_)        // same category, different dates?
            return dateKey_ < other.dateKey_;  // older date = lower priority
        return sequence_ < other.sequence_;    // same date: earlier arrival is lower
    }

    // Print this email in the NEXT command format
    void display(std::ostream& out) const {
        out << "Next email:\n";                    // header line
        out << "\tSender: " << sender_ << "\n";    // tab-indented sender
        out << "\tSubject: " << subject_ << "\n";  // tab-indented subject
        out << "\tDate: " << date_ << "\n";        // tab-indented date
    }

private:
    std::string sender_;   // sender category, e.g. "Boss"
    std::string subject_;  // subject line (may contain spaces)
    std::string date_;     // original date text, e.g. "01-03-2025"
    int rank_;             // numeric category priority (5 = Boss ... 1 = OtherPerson)
    long dateKey_;         // date as YYYYMMDD so newer dates are larger numbers
    long sequence_;        // order the email was added (later = larger)

    // Map a sender category to its priority rank (higher = read sooner)
    static int categoryRank(const std::string& sender) {
        if (sender == "Boss") return 5;             // read first
        if (sender == "Subordinate") return 4;      // read second
        if (sender == "Peer") return 3;             // read third
        if (sender == "ImportantPerson") return 2;  // read fourth
        if (sender == "OtherPerson") return 1;      // read last
        return 0;                                   // unknown category: lowest
    }

    // Convert "MM-DD-YYYY" into the number YYYYMMDD for easy comparison
    static long dateToKey(const std::string& date) {
        std::istringstream in(date);  // stream over the date text
        int month = 0;                // month part
        int day = 0;                  // day part
        int year = 0;                 // year part
        char dash1 = 0;               // first '-' separator
        char dash2 = 0;               // second '-' separator
        if (in >> month >> dash1 >> day >> dash2 >> year)          // parse all parts
            return static_cast<long>(year) * 10000L + month * 100L + day;  // YYYYMMDD
        return 0;                     // malformed date sorts as oldest
    }
};

/* ----------------------------------------------------------------------------
 * MaxHeap class template (source: Claude)
 * A list-based binary max heap built from scratch on a std::vector.
 * For the element at index i:
 *     parent = (i - 1) / 2, left child = 2i + 1, right child = 2i + 2
 * T must provide operator< meaning "lower priority than".
 * ------------------------------------------------------------------------- */
template <typename T>
class MaxHeap {
public:
    // Add an item to the end of the list, then move it up to its spot
    void insert(const T& item) {
        items_.push_back(item);          // place new item at the next open slot
        siftUp(items_.size() - 1);       // restore heap order upward
    }

    // Return the highest-priority item (caller must check isEmpty() first)
    const T& top() const {
        return items_.front();           // the root holds the maximum
    }

    // Remove the highest-priority item; does nothing if the heap is empty
    void removeTop() {
        if (items_.empty()) return;      // nothing to remove
        items_.front() = items_.back();  // move last item into the root
        items_.pop_back();               // drop the now-duplicate last slot
        if (!items_.empty())             // if anything is left...
            siftDown(0);                 // ...restore heap order downward
    }

    // Number of items currently stored
    std::size_t size() const {
        return items_.size();            // vector size is the heap size
    }

    // True when the heap has no items
    bool isEmpty() const {
        return items_.empty();           // vector empty means heap empty
    }

private:
    std::vector<T> items_;  // the list that stores the heap level by level

    // Index of the parent of node i
    static std::size_t parent(std::size_t i) { return (i - 1) / 2; }

    // Index of the left child of node i
    static std::size_t leftChild(std::size_t i) { return 2 * i + 1; }

    // Index of the right child of node i
    static std::size_t rightChild(std::size_t i) { return 2 * i + 2; }

    // Move the item at index i up while it outranks its parent
    void siftUp(std::size_t i) {
        while (i > 0 && items_[parent(i)] < items_[i]) {  // parent is lower priority
            std::swap(items_[i], items_[parent(i)]);      // swap child and parent
            i = parent(i);                                // continue from parent's spot
        }
    }

    // Move the item at index i down while a child outranks it
    void siftDown(std::size_t i) {
        const std::size_t n = items_.size();               // number of items in heap
        while (true) {                                     // loop until settled
            std::size_t largest = i;                       // assume current is largest
            const std::size_t left = leftChild(i);         // left child index
            const std::size_t right = rightChild(i);       // right child index
            if (left < n && items_[largest] < items_[left])    // left child is higher?
                largest = left;                                // remember left
            if (right < n && items_[largest] < items_[right])  // right child is higher?
                largest = right;                               // remember right
            if (largest == i) break;                       // heap order restored
            std::swap(items_[i], items_[largest]);         // swap with larger child
            i = largest;                                   // continue from child's spot
        }
    }
};

/* ----------------------------------------------------------------------------
 * CEOInbox class (source: Claude)
 * The CEO's priority queue of unread emails. Wraps a MaxHeap<Email> and
 * provides one method per test-file command.
 * ------------------------------------------------------------------------- */
class CEOInbox {
public:
    // Start with an empty inbox and arrival counter at zero
    CEOInbox() : nextSequence_(0) {}

    // EMAIL command: add a new email to the priority queue
    void addEmail(const std::string& sender, const std::string& subject,
                  const std::string& date) {
        heap_.insert(Email(sender, subject, date, nextSequence_++));  // insert and bump counter
    }

    // NEXT command: show the highest-priority email without removing it
    void showNext(std::ostream& out) const {
        if (heap_.isEmpty()) {                 // no emails left?
            out << "No emails to read.\n\n";   // tell the user, then blank line
            return;                            // nothing else to show
        }
        heap_.top().display(out);              // print the top email
        out << "\n";                           // blank line after the block
    }

    // READ command: the CEO dealt with the top email, so remove it
    void readEmail() {
        heap_.removeTop();                     // safe even when the heap is empty
    }

    // COUNT command: show how many unread emails remain
    void showCount(std::ostream& out) const {
        out << "There are " << heap_.size()    // current number of emails
            << " emails to read.\n\n";         // message plus blank line
    }

private:
    MaxHeap<Email> heap_;  // priority queue of unread emails
    long nextSequence_;    // arrival order assigned to the next email
};

/* ----------------------------------------------------------------------------
 * CommandProcessor class (source: Claude)
 * Reads the test file line by line, parses each command, and calls the
 * matching CEOInbox method.
 * ------------------------------------------------------------------------- */
class CommandProcessor {
public:
    // Keep a reference to the inbox that commands will act on
    explicit CommandProcessor(CEOInbox& inbox) : inbox_(inbox) {}

    // Open the file and process every line; returns false if it cannot open
    bool processFile(const std::string& fileName) {
        std::ifstream file(fileName.c_str());  // open the test file
        if (!file) {                           // did the open fail?
            std::cerr << "Error: could not open file \"" << fileName << "\"\n";  // report it
            return false;                      // signal failure to caller
        }
        std::string line;                      // holds one line of the file
        while (std::getline(file, line))       // read until end of file
            processLine(line);                 // handle each line
        return true;                           // file processed successfully
    }

private:
    CEOInbox& inbox_;  // the inbox that receives the commands

    // Remove leading/trailing whitespace (also strips Windows '\r')
    static std::string trim(const std::string& text) {
        std::size_t start = 0;                         // first non-space index
        std::size_t end = text.size();                 // one past last non-space
        while (start < end && std::isspace(static_cast<unsigned char>(text[start])))
            ++start;                                   // skip leading spaces
        while (end > start && std::isspace(static_cast<unsigned char>(text[end - 1])))
            --end;                                     // skip trailing spaces / '\r'
        return text.substr(start, end - start);        // return the trimmed part
    }

    // Decide which command a line holds and run it
    void processLine(const std::string& rawLine) {
        const std::string line = trim(rawLine);        // clean up the line
        if (line.empty()) return;                      // skip blank lines
        if (line.compare(0, 5, "EMAIL") == 0 && line.size() > 5 &&
            std::isspace(static_cast<unsigned char>(line[5]))) {  // "EMAIL " prefix?
            processEmail(line.substr(6));              // parse the email fields
        } else if (line == "NEXT") {                   // NEXT command
            inbox_.showNext(std::cout);                // show top email
        } else if (line == "READ") {                   // READ command
            inbox_.readEmail();                        // remove top email
        } else if (line == "COUNT") {                  // COUNT command
            inbox_.showCount(std::cout);               // show unread count
        }                                              // unknown lines are ignored
    }

    // Split "<sender>,<subject>,<date>" and add the email to the inbox
    void processEmail(const std::string& fields) {
        const std::size_t firstComma = fields.find(',');   // end of sender field
        const std::size_t lastComma = fields.rfind(',');   // start of date field
        if (firstComma == std::string::npos || firstComma == lastComma)
            return;                                        // malformed line: skip it
        const std::string sender = trim(fields.substr(0, firstComma));  // sender text
        const std::string subject = trim(fields.substr(firstComma + 1,
                                         lastComma - firstComma - 1));  // subject text
        const std::string date = trim(fields.substr(lastComma + 1));    // date text
        inbox_.addEmail(sender, subject, date);            // queue the email
    }
};

/* ----------------------------------------------------------------------------
 * EmailPriorityApp class (source: Claude)
 * Top-level application object: gets the file name and runs the processor.
 * ------------------------------------------------------------------------- */
class EmailPriorityApp {
public:
    // Wire the command processor to this app's inbox
    EmailPriorityApp() : processor_(inbox_) {}

    // Run the program; returns the process exit code
    int run(int argc, char* argv[]) {
        const std::string fileName = getFileName(argc, argv);  // find the test file
        return processor_.processFile(fileName) ? 0 : 1;       // 0 = success, 1 = error
    }

private:
    CEOInbox inbox_;              // the CEO's email priority queue
    CommandProcessor processor_;  // reads and executes commands on inbox_

    // Use the command-line argument if present, otherwise ask the user
    std::string getFileName(int argc, char* argv[]) const {
        if (argc > 1) return argv[1];         // file name given on command line
        std::string name;                     // holds the typed file name
        std::cout << "Enter test file name: ";  // prompt the user
        std::getline(std::cin, name);         // read the whole line
        return name;                          // return what was typed
    }
};

/* ----------------------------------------------------------------------------
 * main (source: Claude)
 * Creates the application object and starts it.
 * ------------------------------------------------------------------------- */
int main(int argc, char* argv[]) {
    EmailPriorityApp app;        // create the application object
    return app.run(argc, argv);  // run it and return its exit code
}
