/*
 * Program Name: EECS 348 Assignment 3 - CEO Email Priority Queue
 * Program Description:
 *   This C++ program reads EMAIL, NEXT, READ, and COUNT commands from a test file and manages
 *   a priority queue for a CEO's inbox. Priority is determined first by sender category
 *   (Boss > Subordinate > Peer > ImportantPerson > OtherPerson) and second by date (newer
 *   emails have higher priority). The queue is managed using an object-oriented, list-based
 *   MaxHeap implemented from scratch.
 *
 * Inputs:
 *   A test file of commands (EMAIL, NEXT, READ, COUNT). The file name can be given as a
 *   command-line argument (./Gemini_Ceo_Inbox test.txt). If no file name is given, the
 *   commands are read from standard input (./Gemini_Ceo_Inbox < test.txt).
 *
 * Outputs:
 *   Terminal output for the COUNT and NEXT commands in the format given in the assignment
 *   directions, or an error message if the test file cannot be opened.
 *
 * Collaborators:
 *   None
 *
 * Other Sources:
 *   - Original code generated by Google Gemini
 * 
 *
 * Author's Full Name: Erick Marte
 * Creation Date: October 1, 2026
 * Revision Date: October 1, 2026
 * Revisions:
 *   - Oct 01, 2026: Initial implementation of MaxHeap and Email object structure.
 *   - Oct 01, 2026: Removed incorrect author and collaborator comments.
 *   - Oct 01, 2026: Output now matches the required format (tab-indented fields and a blank
 *                   line between output blocks).
 *   - Oct 01, 2026: The test file can be given as a command-line argument; standard input
 *                   still works when no file name is given.
 *   - Oct 01, 2026: Fixed the two signed/unsigned compiler warnings (heap indexes are size_t).
 *   - Oct 01, 2026: Time and space improvements: '\n' instead of endl, date stored as an int,
 *                   sender stored only as its rank, siftDown uses a loop instead of recursion,
 *                   getMax returns a reference instead of a copy, emails are moved instead of
 *                   copied, EMAIL lines are parsed without a stringstream, unused code removed.
 */

#include <iostream>  // Included for standard console input/output operations
#include <fstream>   // Included for reading the test file named on the command line
#include <string>    // Included for std::string handling and operations
#include <vector>    // Included for dynamic list-based underlying container
#include <utility>   // Included for std::swap and std::move used by the heap
#include <cstdio>    // Included for std::sscanf used to parse dates

using namespace std; // Using standard namespace to simplify terminal I/O code

// Enum representing the priority rank of different sender categories
enum PriorityRank {
    BOSS = 5,             // Highest priority category
    SUBORDINATE = 4,      // Second priority category
    PEER = 3,             // Third priority category
    IMPORTANT_PERSON = 2, // Fourth priority category
    OTHER_PERSON = 1      // Lowest priority category
};

// Class representing an individual Email object
// The sender is stored only as its rank, and the date is stored as a number for sorting,
// which keeps each Email small (72 bytes instead of 136) and makes comparisons fast.
class Email {
private:
    string subjectLine;    // Subject line of the email
    string dateStr;        // Date in MM-DD-YYYY format, kept exactly as given for display
    int categoryRank;      // Priority rank integer derived from sender category
    int dateKey;           // Date as the number YYYYMMDD so newer dates compare as larger

    // Helper method to convert category string to priority rank enum value
    static int parseCategoryRank(const string& category) {
        if (category == "Boss") return BOSS;                        // Map "Boss" to rank 5
        if (category == "Subordinate") return SUBORDINATE;          // Map "Subordinate" to rank 4
        if (category == "Peer") return PEER;                        // Map "Peer" to rank 3
        if (category == "Important Person" || category == "ImportantPerson")
            return IMPORTANT_PERSON;                                // Map "ImportantPerson" to rank 2
        return OTHER_PERSON;                                        // Default remaining categories to rank 1
    }

    // Helper method to convert MM-DD-YYYY into the number YYYYMMDD for fast comparison
    static int convertDateToKey(const string& date) {
        int month = 0;                                              // Month part of the date
        int day = 0;                                                // Day part of the date
        int year = 0;                                               // Year part of the date
        if (sscanf(date.c_str(), "%d-%d-%d", &month, &day, &year) == 3) // Read all three parts
            return year * 10000 + month * 100 + day;                // Combine into the number YYYYMMDD
        return 0;                                                   // Malformed date sorts as the oldest
    }

public:
    // Default constructor
    Email() : categoryRank(0), dateKey(0) {}                        // Empty email with the lowest priority

    // Parameterized constructor initializing all fields and derived metrics
    Email(const string& category, const string& subject, const string& date)
        : subjectLine(subject),                                     // Store subject line string
          dateStr(date),                                            // Store original date string for display
          categoryRank(parseCategoryRank(category)),                // Calculate and store category rank
          dateKey(convertDateToKey(date)) {}                        // Calculate and store numeric date key

    // Getter methods (return references or fixed text so nothing is copied)
    const char* getSenderCategory() const {                         // Rebuild the sender name from its rank
        switch (categoryRank) {                                     // Pick the name that matches the rank
            case BOSS: return "Boss";                               // Rank 5
            case SUBORDINATE: return "Subordinate";                 // Rank 4
            case PEER: return "Peer";                               // Rank 3
            case IMPORTANT_PERSON: return "ImportantPerson";        // Rank 2
            default: return "OtherPerson";                          // Rank 1
        }
    }
    const string& getSubjectLine() const { return subjectLine; }    // Returns subject line without copying it
    const string& getDateStr() const { return dateStr; }            // Returns original date without copying it

    // Greater-than operator overloaded to define MaxHeap priority evaluation
    // Priority rule: Higher category rank first; if tied, newer date first.
    bool operator>(const Email& other) const {
        if (this->categoryRank != other.categoryRank) {             // Compare priority categories first
            return this->categoryRank > other.categoryRank;         // Higher category rank takes higher priority
        }
        return this->dateKey > other.dateKey;                       // Newer (larger) date takes higher priority when categories match
    }
};

// Object-Oriented List-Based MaxHeap implementation for Email objects
class MaxHeap {
private:
    vector<Email> heap; // Internal list-based dynamic array container

    // Helper method to return parent index for given node index
    static size_t parent(size_t i) { return (i - 1) / 2; }          // Calculate parent index in continuous heap storage

    // Helper method to return left child index for given node index
    static size_t leftChild(size_t i) { return (2 * i) + 1; }       // Calculate left child index in continuous heap storage

    // Helper method to return right child index for given node index
    static size_t rightChild(size_t i) { return (2 * i) + 2; }      // Calculate right child index in continuous heap storage

    // Sift node up to maintain heap property after insertion
    void siftUp(size_t i) {
        while (i > 0 && heap[i] > heap[parent(i)]) {               // Loop while node is greater than parent
            swap(heap[i], heap[parent(i)]);                        // Swap node with its parent element
            i = parent(i);                                         // Move index up to parent position
        }
    }

    // Sift node down to maintain heap property after removal
    // Uses a loop instead of recursion so no extra stack space is needed.
    void siftDown(size_t i) {
        const size_t n = heap.size();                              // Number of elements currently in the heap
        while (true) {                                             // Repeat until the node is in its correct place
            size_t maxIndex = i;                                   // Assume current node is maximum
            size_t left = leftChild(i);                            // Get index of left child
            size_t right = rightChild(i);                          // Get index of right child

            if (left < n && heap[left] > heap[maxIndex]) {         // Check if left child exists and is larger
                maxIndex = left;                                   // Update maxIndex to left child
            }

            if (right < n && heap[right] > heap[maxIndex]) {       // Check if right child exists and is larger
                maxIndex = right;                                  // Update maxIndex to right child
            }

            if (maxIndex == i) {                                   // If the current node is already the largest
                break;                                             // Heap order is restored, so stop
            }

            swap(heap[i], heap[maxIndex]);                         // Swap current node with larger child
            i = maxIndex;                                          // Continue sifting from the child's position
        }
    }

public:
    // Constructor
    MaxHeap() {}                                                   // Default constructor initializing empty heap

    // Check if heap is empty
    bool isEmpty() const { return heap.empty(); }                  // Return true if internal list contains no elements

    // Get number of elements in heap
    size_t size() const { return heap.size(); }                    // Return current count of elements stored

    // Insert a new Email into heap
    void insert(Email email) {
        heap.push_back(move(email));                               // Move new email to end of dynamic array (no extra copy)
        siftUp(heap.size() - 1);                                   // Re-establish heap order starting from new element
    }

    // Peek at maximum priority element without removing it
    const Email& getMax() const {
        static const Email emptyEmail;                             // Placeholder returned only if the heap is empty
        if (!heap.empty()) return heap[0];                         // Return root element by reference (no copy)
        return emptyEmail;                                         // Return placeholder if heap is empty
    }

    // Extract and remove maximum priority element
    void extractMax() {
        if (heap.empty()) return;                                  // Do nothing if heap is empty
        heap[0] = move(heap.back());                               // Move last element into the root (no string copies)
        heap.pop_back();                                           // Remove last element from array
        if (!heap.empty()) siftDown(0);                            // Re-establish heap order starting from root node
    }
};

// Utility function to trim leading and trailing spaces from input strings
string trim(const string& str) {
    size_t first = str.find_first_not_of(" \t\r\n");               // Locate first non-whitespace character
    if (first == string::npos) return "";                          // Return empty string if only whitespace
    size_t last = str.find_last_not_of(" \t\r\n");                 // Locate last non-whitespace character
    return str.substr(first, (last - first + 1));                  // Return sliced string without surrounding whitespace
}

// Main execution function
int main(int argc, char* argv[]) {
    ifstream inputFile;                                            // File stream used when a file name is given
    if (argc > 1) {                                                // Check if a test file was named on the command line
        inputFile.open(argv[1]);                                   // Try to open the named file
        if (!inputFile) {                                          // Check if the file failed to open
            cerr << "Error: could not open file \"" << argv[1] << "\"\n"; // Report the problem
            return 1;                                              // Exit with an error code
        }
    }
    istream& input = (argc > 1) ? static_cast<istream&>(inputFile) : cin; // Read from the file if given, otherwise from standard input

    MaxHeap inboxQueue;                                            // Instantiate MaxHeap priority queue object
    string line;                                                   // Buffer variable to hold each line read
    bool printedBlock = false;                                     // Tracks whether any output has been printed yet

    while (getline(input, line)) {                                 // Read input line-by-line until end of file
        line = trim(line);                                         // Strip extra trailing/leading whitespace
        if (line.empty()) continue;                                // Skip processing if line is empty

        if (line.compare(0, 6, "EMAIL ") == 0) {                   // Check if line begins with command "EMAIL "
            size_t firstComma = line.find(',', 6);                 // Find the comma after the sender category
            size_t lastComma = line.rfind(',');                    // Find the comma before the date
            if (firstComma == string::npos || firstComma == lastComma) continue; // Skip EMAIL lines missing a field

            string category = trim(line.substr(6, firstComma - 6));                       // Extract and trim sender category
            string subject = trim(line.substr(firstComma + 1, lastComma - firstComma - 1)); // Extract and trim subject line
            string date = trim(line.substr(lastComma + 1));                               // Extract and trim date string

            inboxQueue.insert(Email(category, subject, date));     // Build the Email and push it onto the MaxHeap
        }
        else if (line == "COUNT") {                                // Process "COUNT" command
            if (printedBlock) cout << '\n';                        // Blank line separates this from the previous output
            cout << "There are " << inboxQueue.size()
                 << " emails to read.\n";                          // Display current unread email count
            printedBlock = true;                                   // Remember that output has been printed
        }
        else if (line == "NEXT") {                                 // Process "NEXT" command
            if (!inboxQueue.isEmpty()) {                           // If queue has pending emails
                if (printedBlock) cout << '\n';                    // Blank line separates this from the previous output
                const Email& top = inboxQueue.getMax();            // Look at highest priority email without copying it
                cout << "Next email:\n";                           // Print required output header
                cout << "\tSender: " << top.getSenderCategory() << '\n'; // Display tab-indented sender category
                cout << "\tSubject: " << top.getSubjectLine() << '\n';   // Display tab-indented subject line
                cout << "\tDate: " << top.getDateStr() << '\n';          // Display tab-indented email date
                printedBlock = true;                               // Remember that output has been printed
            }
        }
        else if (line == "READ") {                                 // Process "READ" command
            if (!inboxQueue.isEmpty()) {                           // If queue has pending emails
                inboxQueue.extractMax();                           // Remove top priority email from heap queue
            }
        }
    }

    return 0;                                                      // Exit program execution successfully
}
